spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 30000ms
    database: 0
    lettuce:
      pool:
        max-active: 1024
        max-idle: 50
        min-idle: 1
        max-wait: 5000